config/routes.rb
NicksListAdminProj::Application.routes.draw do
  
  post "/reports/ViewFAQ"
  get"/reports/ViewFAQ"
  post "/reports/ViewTestimonials"
  get"/reports/ViewTestimonials"
  post "/reports/ViewNewsUpdate"
  get"/reports/ViewNewsUpdate"
  post "/reports/ViewSiteContent"
  get"/reports/ViewSiteContent"
  post "/reports/ViewMLJudgements"
  get"/reports/ViewMLJudgements"
  post "/reports/ViewCourtProceedings"
  get "/reports/ViewCourtProceedings"
  post "/reports/AdminActivityReport"
  get"/reports/AdminActivityReport"
  post "/reports/AdminActivityDetails"
  get "/reports/AdminActivityDetails"
  post "/reports/ViewReview"
  get "/reports/ViewReview"
  post "/reports/ViewUser"
  get "/reports/ViewUser"
  post "/reports/ViewAdmin"
  get "/reports/ViewAdmin"
  post "/reports/ViewCustomerSearchBy"
  get "/reports/ViewCustomerSearchBy"
  post "/reports/CustomerSearchReport"
  get "/reports/CustomerSearchReport"
  post "/reports/UserLoginReport"
  get "/reports/UserLoginReport"
  post "/reports/AdminLoginReport"
  get "/reports/AdminLoginReport"
  post "/reports/ViewUserLoginHistory"
  get "/reports/ViewUserLoginHistory"
  post "/reports/ViewAdminLoginHistory"
  get "/reports/ViewAdminLoginHistory"
  
  post "/sitecontent/EditBannerText"
  get "/sitecontent/EditBannerText"
  post "/sitecontent/EnableDisableFAQ"
  get "/sitecontent/EnableDisableFAQ"
  post "/sitecontent/AddFAQPage"
  get "/sitecontent/AddFAQPage"
  post "/sitecontent/AddUpdateFAQPage"
  get "/sitecontent/AddUpdateFAQPage"
  post "/sitecontent/DeleteFAQPage"
  get "/sitecontent/DeleteFAQPage"
  post "/sitecontent/EditFAQPage"
  get "/sitecontent/EditFAQPage"
  post "/sitecontent/ManageFAQPage"
  get "/sitecontent/ManageFAQPage"
  
  post "/sitecontent/EnableDisableNewsUpdate"
  get "/sitecontent/EnableDisableNewsUpdate"
  post "/sitecontent/AddNewsUpdatePage"
  get "/sitecontent/AddNewsUpdatePage"
  post "/sitecontent/AddUpdateNewsUpdatePage"
  get "/sitecontent/AddUpdateNewsUpdatePage"
  post "/sitecontent/DeleteNewsUpdatePage"
  get "/sitecontent/DeleteNewsUpdatePage"
  post "/sitecontent/EditNewsUpdatePage"
  get "/sitecontent/EditNewsUpdatePage"
  post "/sitecontent/ManageNewsUpdatePage"
  get "/sitecontent/ManageNewsUpdatePage"
  
  post "/sitecontent/EnableDisableTestimonials"
  get "/sitecontent/EnableDisableTestimonials"
  post "/sitecontent/AddTestimonialsPage"
  get "/sitecontent/AddTestimonialsPage"
  post "/sitecontent/AddUpdateTestimonialsPage"
  get "/sitecontent/AddUpdateTestimonialsPage"
  post "/sitecontent/DeleteTestimonialsPage"
  get "/sitecontent/DeleteTestimonialsPage"
  post "/sitecontent/EditTestimonialsPage"
  get "/sitecontent/EditTestimonialsPage"
  post "/sitecontent/ManageTestimonialsPage"
  get "/sitecontent/ManageTestimonialsPage"
  
  post "/sitecontent/UpdateSiteContent"
  get "/sitecontent/UpdateSiteContent"
  
  post "/sitecontent/EditAboutPage"
  get "/sitecontent/EditAboutPage"
  
  post "/sitecontent/EditHowItWorksPage"
  get "/sitecontent/EditHowItWorksPage"
  
  post "/sitecontent/EditPressReleasePage"
  get "/sitecontent/EditPressReleasePage"
  
  post "/sitecontent/EditPrivacyPolicy"
  get "/sitecontent/EditPrivacyPolicy"
  
  post "/sitecontent/EditTermsConditions"
  get "/sitecontent/EditTermsConditions"
  
  post "/public_records/UpdateCourtProceedings"
  get "/public_records/UpdateCourtProceedings"
  post "/public_records/EditCourtProceedings"
  get "/public_records/EditCourtProceedings"
  
  post "/public_records/UpdateMLJudgements"
  get "/public_records/UpdateMLJudgements"
  post "/public_records/EditMLJudgements"
  get "/public_records/EditMLJudgements"
  
  post "/public_records/ManagePublicRecords"
  get "/public_records/ManagePublicRecords"
  
  post "/site_users/AddUser"
  get "/site_users/AddUser"
  post "/site_users/ManageUsers"
  get "/site_users/ManageUsers"
  post "/site_users/EditUser"
  get "/site_users/EditUser"
  post "/site_users/UpdateUser"
  get "/site_users/UpdateUser"
  
  post "/site_users/EditRoles"
  get "/site_users/EditRoles"
  post "/site_users/AddUpdateRoles"
  get "/site_users/AddUpdateRoles"
  
  post "/site_users/ChangePassword"
  get "/site_users/ChangePassword"
  
  post "/site_users/UserActivation"
  get "/site_users/UserActivation"
  
  post "/users/ChangePassword"
  get "/users/ChangePassword"
  post "/users/AddUser"
  get "/users/AddUser"
  post "/users/ManageUsers"
  get "/users/ManageUsers"
  post "/users/DeleteUser"
  get "/users/DeleteUser"
  post "/users/EditUser"
  get "/users/EditUser"
  post "/users/UpdateUser"
  get "/users/UpdateUser"
  post "/users/UserActivation"
  get "/users/UserActivation"
  post "/users/SearchNotification"
  get "/users/SearchNotification"
  
  post "/reviews/ManageReviews"
  get "/reviews/ManageReviews"
  post "/reviews/EditReview"
  get "/reviews/EditReview"
  post "/reviews/UpdateReview"
  get "/reviews/UpdateReview"
  post "/reviews/PublishReview"
  get "/reviews/PublishReview"
  post "/reviews/ApproveReview"
  get "/reviews/ApproveReview"
  
  post "/user_profile/EditProfile"
  get "/user_profile/EditProfile"
  post "/user_profile/ViewProfile"
  get "/user_profile/ViewProfile"
  post "/user_profile/UpdateProfile"
  get "/user_profile/UpdateProfile"
    
  post "/authentication/ChangePassword"
  get "/authentication/ChangePassword"
  post "/authentication/SavePassword"
  get "/authentication/SavePassword"
  post "/authentication/requestpassword"
  get "/authentication/requestpassword"
  
  post "/authentication/login"
  get "/authentication/login"
  
  post "/authentication/logout"
  get "/authentication/logout"
  
  post "/customer_search/LoadReviews"
  get "/customer_search/LoadReviews"
  
  post "/nicks_admin/Index"
  get "/nicks_admin/Index"
  root to: "nicks_admin#Index"
  

  

end

app/models/admin_activity.rb
class AdminActivity < ActiveRecord::Base
end

app/models/customer_phone.rb
class CustomerPhone < ActiveRecord::Base
end

app/models/defendants.rb
class Defendants < ActiveRecord::Base
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/faq_history.rb
class FaqHistory < ActiveRecord::Base
end

app/models/grantors.rb
class Grantors < ActiveRecord::Base
end

app/models/key.rb
class Key < ActiveRecord::Base
end

app/models/liens.rb
class Liens < ActiveRecord::Base
end

app/models/liens_history.rb
class LiensHistory < ActiveRecord::Base
end

app/models/ml_judgements.rb
class MlJudgements < ActiveRecord::Base
end

app/models/news_updates.rb
class NewsUpdates < ActiveRecord::Base
end

app/models/operation_list.rb
class OperationList < ActiveRecord::Base
end

app/models/plaintiffs.rb
class Plaintiffs < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/review_answer.rb
class ReviewAnswer < ActiveRecord::Base
end

app/models/site_content.rb
class SiteContent < ActiveRecord::Base
end

app/models/site_module.rb
class SiteModule < ActiveRecord::Base
end

app/models/site_user.rb
class SiteUser < ActiveRecord::Base
end

app/models/testimonials.rb
class Testimonials < ActiveRecord::Base
end

app/controllers/nicks_admin_controller.rb
class NicksAdminController < ApplicationController
  skip_before_action :verify_authenticity_token
  def Index
    @openLogin = ''
    if(!flash[:userName].blank? && !flash[:error].blank?)
      @openLogin = 1
      @userName = flash[:userName]
      @errorMessage = flash[:error]
    end
    
    if(!flash[:redirectUrl].blank?)
      @openLogin = 1
      @redirectUrl = flash[:redirectUrl]
    end   
  end
  
  def About
    
  end
  
  def HowItWorks
    
  end
end

app/helpers/nicks_admin_helper.rb
module NicksAdminHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/nicks_admin/Index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Nick's List</title>
		<script type="text/javascript">
			function openLogin(val) {
				if (val != '' && val != null) {
					$('#signin_menu').show();
				}
			}
		</script>
	</head>
	<body onload="openLogin('<%= @openLogin %>');">

		<div id="wrapper">
			<div id="header-wrapper">
				<div class="browser-center">
					<div id="header-area">
						<div id="logo">
							<a href="/"><%= image_tag("logo.jpg", :alt => "") %></a>
						</div>
						<div id="facebook-like">
							<%= image_tag("facebook-like.jpg", :alt => "") %>
						</div>
						<div id="customer-support">
							<p>
								Customer Support
							</p>
							<h1>703 555 5555</h1>
							<p>
								Any Questions <a href="mailto:">Email Us</a>
							</p>
						</div>
						<div id="navigation">
							<div id="nav">
								<ul>
									<li>
								<a href="<%= nicks_admin_Index_path %>">Home</a>
							</li>
							<li>
								<a href="<%= site_users_ManageUsers_url %>">Admins</a>
							</li>
							<li>
								<a href="<%= users_ManageUsers_url %>">Users</a>
							</li>
							<li>
								<a href="<%= reviews_ManageReviews_url %>">Reviews</a>
							</li>
							<li>
								<a href="<%= public_records_ManagePublicRecords_url %>">Public Records</a>
							</li>
							<li>
									<a href="javascript:void(0)">Site Content</a>
								
									<ul>
										<li>
											<a href="<%= sitecontent_EditAboutPage_url %>">About BillyList</a>
										</li>
										<li>
											<a href="<%= sitecontent_EditBannerText_url %>">Banner</a>
										</li>
										<li>
											<a href="<%= sitecontent_EditHowItWorksPage_url %>">How It Works</a>
										</li>
										<li>
											<a href="<%= sitecontent_EditPressReleasePage_url %>">Press Release</a>
										</li>
										<li>
											<a href="<%= sitecontent_EditPrivacyPolicy_url %>">Privacy Policy</a>
										</li>
										<li>
											<a href="<%= sitecontent_EditTermsConditions_url %>">Terms/Conditions</a>
										</li>
										<li>
											<a href="<%= sitecontent_ManageFAQPage_url %>">FAQ's</a>
										</li>
										<li>
											<a href="<%= sitecontent_ManageTestimonialsPage_url %>">Testimonials</a>
										</li>
										<li>
											<a href="<%= sitecontent_ManageNewsUpdatePage_url %>">News/Updates</a>
										</li>
										
									</ul>
									
							</li>
							<li>
									<a href="javascript:void(0)">Reports</a>
								
									<ul>
										<li>
											<a href="<%= reports_AdminLoginReport_url %>">Admin Login</a>
										</li>
										<li>
											<a href="<%= reports_AdminActivityReport_url %>">Admin Activity</a>
										</li>
										<li>
											<a href="<%= reports_UserLoginReport_url %>">User Login</a>
										</li>
										<li>
											<a href="<%= reports_CustomerSearchReport_url %>">Customer Search</a>
										</li>
									</ul>
									
							</li>
								</ul>
							</div>
							<div class="login-wrapper">
								<% if(session[:user_id] == nil) %>
								<div id="login-reg" class="login-register">
									<a href="javascript:void(0)">Login / Register</a>
								</div>
								<div id="signin_menu">
									<form action="<%= authentication_login_url %>" method="post">
										<p>
											<label for="username">Username</label>
											<input id="textUserName" name="textUserName" required="required" value="<%= @userName %>" title="User Name" tabindex="4" type="text">
										</p>
										<p>
											<label for="password">Password</label>
											<input id="textPassword" name="textPassword" required="required" value="" title="password" tabindex="5" type="password">
										</p>
										<% if(!@errorMessage.blank?) %>
										<div id="Error">
											<%= @errorMessage %>
										</div>
										<% end %>
										<p class="remember">

											<input type="hidden" name="hidFirstName" id="hidFirstName" value="<%= @firstName %>" />
											<input type="hidden" name="hidLastName" id="hidLastName" placeholder="Last Name" value="<%= @lastName %>" />
											<input type="hidden" name="hidStreetAddress" id="hidStreetAddress" placeholder="Street Address" value="<%= @streetAddress %>" />
											<input type="hidden" name="hidselectCity" id="hidselectCity" placeholder="City, State" value="<%= @citystateVal %>" />
											<input type="hidden" name="hidZipCode" id="hidZipCode" placeholder="Zipcode" value="<%= @zipCode %>" />
											<input type="hidden" name="hidPhoneNumber" id="hidPhoneNumber" placeholder="Phone Number" value="<%= @phoneNumber %>" />
											<input type="hidden" name="hidredirectUrl" id="hidredirectUrl" value="<%= @redirectUrl %>" />
											<input type="hidden" name="hidReviewerID" id="hidReviewerID" value="<%= @reviewerID %>" />
											<input type="hidden" name="hidReviewID" id="hidReviewID" value="<%= @reviewID %>" />
											<input type="hidden" name="hidReviewCount" id="hidReviewCount" value="<%= @reviewCount %>" />
											<input id="signin_submit" value="Sign in" tabindex="6" type="submit">
											<!--<input id="remember" name="remember_me" value="1" tabindex="7" type="checkbox">
											<label for="remember">Remember me</label>-->
										</p>

										<p class="forgot">
											<a href="<%= authentication_requestpassword_url %>" id="resend_password_link"><b>Forgot your password?</b></a>
										</p>

									</form>
								</div>
								<% else %>
								<div id="logout-reg" class="logout-register">
									<% @signedUser =SiteUser.find_by(id: session[:user_id]) %>
									<a href="javascript:void(0);"><%= image_tag("user.png", :alt => "",:style => "vertical-align:top", :width => "40px", :height=> "40px") %><%= @signedUser.FirstName %></a>
								</div>
								<div id="signout_menu">
									<form action="<%= user_profile_ViewProfile_url %>" method="post">

										<input id="signout_submit" value="My Profile" tabindex="6" type="submit">

									</form>
									<form action="<%= authentication_logout_url %>" method="post">

										<input id="signout_submit" value="Sign Out" tabindex="6" type="submit">

									</form>
								</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="banner">
				<div class="browser-center">
					<div id="innwe-banner-area">

					</div>
				</div>
			</div>
			<div id="main-content-wrapper">
				<div class="browser-center">
					<div id="three-block">
						<div class="blue-block">
							<%= image_tag("about-icon.png", :alt => "") %>
							<h1>About BillysList</h1>
							<p>
								BillysList.com was founded by a small business owner who realized that just as good people need to beaware of bad contractors; good contractors need to be aware of bad people.
							</p>
						</div>

						<div class="org-block">
							<%= image_tag("how-work.png", :alt => "") %>
							<h1>How it Works</h1>
							<p>
								When you login to BillysList.com you have the option to either rate/review a customer or searchfor info on a potential customer.
							</p>
						</div>

						<div class="blue-block">
							<%= image_tag("testimonial.png", :alt => "") %>
							<h1>Client Testimonials</h1>
							<p>
								There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.
							</p>
						</div>
					</div>
				</div>
			</div>

			<%= render partial: "/layouts/footer" %>
		</div>
	</body>
</html>